name: jasper_wt
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.3
  equatable: ^2.0.5
  firebase_auth: ^4.15.0
  firebase_core: ^2.24.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  google_fonts: ^6.1.0
  hexcolor: ^3.0.1
  uuid: ^4.2.1
  timeago_flutter: ^3.4.0
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
