// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8T-70APk6AmZQ2ttfVgXSaurvY_iFO9Y',
    appId: '1:312368800840:web:5fd51a3d7b78325a3aa47d',
    messagingSenderId: '312368800840',
    projectId: 'jasper-wt',
    authDomain: 'jasper-wt.firebaseapp.com',
    storageBucket: 'jasper-wt.appspot.com',
    measurementId: 'G-3467F59FWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAmgVX11Q7uC8WCRLpx_KUUFpwzVUTjPE',
    appId: '1:312368800840:android:fd49d1b9061cf4a93aa47d',
    messagingSenderId: '312368800840',
    projectId: 'jasper-wt',
    storageBucket: 'jasper-wt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm_MQTrY9U2JmLxOAG0fdzPtfphP7ztSk',
    appId: '1:312368800840:ios:9955340a7da029b83aa47d',
    messagingSenderId: '312368800840',
    projectId: 'jasper-wt',
    storageBucket: 'jasper-wt.appspot.com',
    iosBundleId: 'com.example.jasperWt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm_MQTrY9U2JmLxOAG0fdzPtfphP7ztSk',
    appId: '1:312368800840:ios:f04ae7d8e21d30a43aa47d',
    messagingSenderId: '312368800840',
    projectId: 'jasper-wt',
    storageBucket: 'jasper-wt.appspot.com',
    iosBundleId: 'com.example.jasperWt.RunnerTests',
  );
}
